### PR TITLE
Modifying internal links

### PR DESCRIPTION
**Pull request by clockback**
Adding github.com/wesnoth/wesnoth as "internal link"

### CODE REVIEW

**Comment by clockback** [comment]
This is so that citations on wiki.wesnoth.org can link to their respective GitHub files without the icon indicating that it is an external link.

**Comment by irydacea** [comment]
GitHub links *are* external, though. Why should we lie about this fact?

**Comment by clockback** [comment]
It is only an external link in so far as sourceforge.net/projects/wesnoth is an external link. To my knowledge, the special CSS for external links is presumably to indicate that the user who follows the link is aware that they are going to some place that is external to the de facto official Wesnoth domain. The GitHub repository for Wesnoth seems to be within that domain, just as the sourceforge project is, so I don't believe anybody is deceived.

But besides the justification for why it isn't inappropriate, I believe it would be undesirable to have extra CSS styling in a citation list on the wiki.

**Comment by irydacea** [comment]
I don't think the citation list argument is particularly relevant. Wikipedia doesn't shy away from including external links in citation lists for example.

I'd like @Vultraz opinion on this. I didn't remember that we made an exception for SF.net.

**Comment by clockback** [comment]
What you mention about Wikipedia is true. At the moment, if I cite a scenario, I format it like this:

A Summer of Storms, The Rise of Wesnoth

The problem is that introducing external links adds two icons. In the first link (to the scenario), it adds "</>" on the left, whereas in the second link (to the campaign), it adds a box with an arrow on the right. See [this article](https://wiki.wesnoth.org/A_Summer_of_Storms) for reference.

The icons are different, and though it is hard to articulate, I personally don't like it from a visual standpoint. Of course, if I am alone in this preference, I don't mind leaving things as they are. :)

**Comment by GregoryLundberg** [comment]
The issue is the definition of "internal" and "external".

From the point of view of the Wiki pages, themselves, SF, GH, etc., are all "external" because they are on different web servers. Technically, even the Forums are "external" because they are not part of the Wiki, itself.

But, from the point of view of the Wesnoth Project, those pages are "internal" since they are official parts of the project, no matter where they reside.

My feeling is the latter is better for our purposes.

Whichever definition is choosen, however, the underlying point from the OP stands: we should, at least, be consistent. If SF is "internal" so is GH; if GH is "external" then SF should be as well.

**Comment by irydacea** [comment]
Going for aesthetics here above everything else since I see that GH links are becoming more common.

**Pull request merged**
